# Automatically welcome new contributors on their first issue and pull request.
# This helps create a welcoming environment and encourages continued contributions.

name: first-interaction
on: [issues, pull_request]

jobs:
  welcome:
    runs-on: ubuntu-22.04
    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for opening your first issue! We appreciate your contribution."
          pr-message: "Thank you for your first pull request! We will review it soon."